import { CANVAS_WIDTH, CANVAS_HEIGHT } from './constants.js';

export const state = {
    score: 0,
    isDragging: false,
    startX: 0,
    startY: 0,
    currentX: 0,
    currentY: 0,
    dt: 1,
    lastTime: 0,
    
    arrows: [],
    target: { x: 900, y: 400, radius: 30, speed: 1.5, direction: 1 },
    boss: { 
        active: false, 
        hp: 500000000, 
        maxHp: 500000000, 
        x: 900, 
        y: 400, 
        radius: 80, 
        phase: 1, 
        lastTeleport: 0, 
        teleportCount: 0, 
        isGroggy: false, 
        groggyEndTime: 0, 
        isCharging: false, 
        chargeStartTime: 0, 
        lastChargeAttackTime: 0, 
        targetX: 0, 
        targetY: 0, 
        starLevel: 0, 
        lastStarUpdateTime: 0,
        gravityEnabled: false,
        gravityStrength: 0.15,
        rifts: [], 
        guardians: [], 
        isBursting: false, 
        timeScale: 1.0,
        lastPatternTime: 0
    },
    playerHP: 100,
    maxPlayerHP: 100,
    floorPatterns: [],
    particles: [],
    combo: 0,
    lastHitTime: 0,
    chargeStartTime: 0,
    shakeAmount: 0,
    ripples: [],
    floatingTexts: [],
    shockwaves: [],
    vortexParticles: [],
    orbitParticles: [],
    bossProjectiles: [],
    currentWeapon: 'bow',
    hammers: [],
    swings: [],
    isHammerThrown: false,
    starLevel: 0,
    targetStarLevel: 0,
    isStarRolled: false,
    lastStarUpdateTime: 0,
    impactFlash: 0,
    lastEvolutionCheck: 0,
    bolts: [],
    isOverloading: false,
    overloadEndTime: 0,

    // Multiplayer
    peer: null,
    conn: null,
    myId: '',
    remotePlayer: {
        x: -100, y: -100,
        hp: 100, maxHp: 100,
        active: false,
        weapon: 'bow',
        isCharging: false,
        chargeProgress: 0
    },
    isPvP: false,
    isCoop: false,
    isHost: false,
    isDead: false,
    invulnerableUntil: 0,
    countdownRemaining: 0
};
